version: 0.0
os: ubuntu
files:
  - source: /
    destination : /var/www/codeigniter-app
permissions:
  - object: /var/www/codeigniter-app
    pattern: '**'
    mode: '0755'
    owner: root
    group: root
    type:
      - file
      - directory
hooks:
  ApplicationStart:
    - location: deploy-scripts/application-start-hook.sh
    timeout: 300