version: 0.0
os: linux
files:
  - source: dist/projeto-loja-online.tar.gz  # Caminho do artefato gerado
    destination: /var/www/codeigniter-app  # Onde o artefato será extraído na EC2
permissions:
  - object: /var/www/codeigniter-app
    pattern: '**'
    mode: '0755'
    owner: root
    group: root
    type:
      - file
      - directory
hooks:
  ApplicationStart:
    - location: deploy-scripts/application-start-hook.sh
    timeout: 300
