version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1 # Define a versão do PHP diretamente, caso a imagem suporte
    commands:
      - echo "Atualizando pacotes..."
      - apt-get update -y
      - echo "Instalando PHP 8.1 e dependências necessárias..."
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:ondrej/php -y
      - apt-get update -y
      - apt-get install -y php8.1 php8.1-cli php8.1-mbstring php8.1-xml php8.1-zip
      - php --version
  pre_build:
    commands:
      - echo "Instalando dependências do Composer..."
      - composer install
  build:
    commands:
      - echo "Executando testes..."
      - ./vendor/bin/phpunit --coverage-text
  post_build:
    commands:
      - echo "Build concluído com sucesso!"
artifacts:
  files:
    - '**/*'
    - '!vendor/**' # Opcional: exclui a pasta de dependências do Composer nos artefatos gerados
    - '!tests/**'  # Opcional: exclui os arquivos de teste
  name: build-output.zip # Opcional: nome do arquivo compactado gerado
cache:
  paths:
    - vendor/** # Armazena o cache da pasta vendor para acelerar builds futuros
