version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.3
    commands:
      - echo "Atualizando pacotes e instalando dependências extras necessárias..."
      - apt-get update -y
      - apt-get install -y php-mbstring php-xml php-zip unzip curl
      - echo "Instalando Composer..."
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - php --version
      - composer --version

  pre_build:
    commands:
      - echo "Instalando dependências do Composer..."
      - composer install

  build:
    commands:
      - echo "Executando testes (placeholder)..."
      - echo "Sem testes configurados ainda. Continuando..."

  post_build:
    commands:
      - echo "Criando o diretório dist..."
      - mkdir -p dist  # Criar o diretório dist, caso não exista
      - echo "Gerando o pacote de distribuição..."
      - tar -cvzf dist/projeto-loja-online.tar.gz -C /var/www codeigniter-app
      - echo "Build concluído com sucesso!"

artifacts:
  files:
    - '**/*'
    - appspec.yml
    - 'deploy-scripts/**/*'
    - dist/projeto-loja-online.tar.gz  # Incluindo o arquivo gerado no dist

cache:
  paths:
    - vendor/**  # Cache para dependências do Composer
