version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.3
    commands:
      - echo "Atualizando pacotes e instalando dependências extras necessárias..."
      - apt-get update -y
      - apt-get install -y php-mbstring php-xml php-zip unzip curl
      - echo "Instalando Composer..."
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - php --version
      - composer --version

  pre_build:
    commands:
      - echo "Instalando dependências do Composer..."
      - composer install

  build:
    commands:
      - echo "Executando testes (placeholder)..."
      - echo "Sem testes configurados ainda. Continuando..."

  post_build:
    commands:
      - echo "Construindo artefato de implantação..."
      - cp appspec.yml dist/  # Copiar o appspec.yml para o diretório de artefato
      - cp -r deploy-scripts/ dist/  # Incluir scripts de deploy
      - cp -r application/ dist/  # Incluir o código fonte
      - echo "Build concluído com sucesso!"

artifacts:
  files:
    - 'dist/**/*'  # Incluir todo o conteúdo da pasta dist
    - appspec.yml  # Incluir o appspec.yml separadamente, se necessário

cache:
  paths:
    - vendor/**  # Cache para dependências do Composer
