version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - echo "Atualizando pacotes e instalando dependências extras necessárias..."
      - apt-get update -y
      - apt-get install -y php8.1-mbstring php8.1-xml php8.1-zip unzip curl
      - echo "Instalando Composer..."
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - php --version
      - composer --version

  pre_build:
    commands:
      - echo "Instalando dependências do Composer..."
      - composer install

  build:
    commands:
      - echo "Executando testes..."
      - composer test:coverage

  post_build:
    commands:
      - echo "Build concluído com sucesso!"

artifacts:
  files:
    - '**/*'
    - '!vendor/**'
    - '!tests/**'

cache:
  paths:
    - vendor/**
