version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.0 # Altere para uma versão suportada
    commands:
      - echo "Atualizando pacotes do sistema..."
      - apt-get update -y
      - echo "Instalando dependências extras se necessário..."
      - apt-get install -y php-mbstring php-xml php-zip unzip curl
      - echo "Instalando Composer..."
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - php --version
      - composer --version

  pre_build:
    commands:
      - echo "Instalando dependências do Composer..."
      - composer install

  build:
    commands:
      - echo "Executando testes com cobertura..."
      - composer test:coverage

  post_build:
    commands:
      - echo "Build concluído com sucesso!"

artifacts:
  files:
    - '**/*'
    - '!vendor/**'
    - '!tests/**'

cache:
  paths:
    - vendor/**
